### ISSUE TITLE
It makes visited link (`a:visited`) texts white

### ISSUE THREAD

**Issue by jaekyeom** [weigq/openview_quicklook#2]
Hi,
It's glad to see that this extension is back! It's really useful.

By the way, I think this extension is making the color of the texts for visited links (`a:visited`) white in openreview, maybe with the following part

```
a,a:active,a:hover,a:visited{color:#fff}
```

or maybe with
https://github.com/weigq/openview_quicklook/blob/2a2860b95718f5605ed7a1e376c4a341045932e5/style.css#L90-L93
before minimization.

When you get some spare time, could you look into that, please?

Thanks!

**Comment by weigq** [comment]
good point, I will fix later.

**Comment by weigq** [comment]
Done!
