### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by louieworth** [weigq/openview_quicklook#3]
This Plugin recently does work. Is there any problem?

**Comment by weigq** [comment]
It works well here. 
can you provide more details?

**Comment by louieworth** [comment]
I think it works again.

**Comment by louieworth** [comment]
I think that I have met the problem again. It only shows whether it is accepted or not. 

<img width="244" alt="image" src="https://github.com/weigq/openview_quicklook/assets/37494792/df00465f-44e3-46f1-943a-b1b44fd4199c">

**Comment by weigq** [comment]
@louieworth can you share a link to openreview and the version of the extension

**Comment by louieworth** [comment]
Openreview: https://openreview.net/forum?id=AOSIbSmQJr
extension: https://chromewebstore.google.com/detail/openreview-quicklook/efoabjckcjahofacmgekfhjadpjlmcap

I think there is no "version" for extension.

**Comment by weigq** [comment]
Thanks, there is some modification of openview api. I have updated a new version to store, and your extension will be updated automatically when the new version is available.
